//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParaEngine.NPLLanguageService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ParaEngine.NPLLanguageService.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create tool window..
        /// </summary>
        internal static string CanNotCreateWindow {
            get {
                return ResourceManager.GetString("CanNotCreateWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create tool window..
        /// </summary>
        internal static string CannotCreateWindow1 {
            get {
                return ResourceManager.GetString("CannotCreateWindow1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ClearFiltersButton {
            get {
                object obj = ResourceManager.GetObject("ClearFiltersButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Outline View.
        /// </summary>
        internal static string CodeOutlineViewCommandName {
            get {
                return ResourceManager.GetString("CodeOutlineViewCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Code Outline View.
        /// </summary>
        internal static string CodeOutlineViewCommandToolTipText {
            get {
                return ResourceManager.GetString("CodeOutlineViewCommandToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Window.
        /// </summary>
        internal static string CodeWindowCommandBarName {
            get {
                return ResourceManager.GetString("CodeWindowCommandBarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ErrorIcon {
            get {
                object obj = ResourceManager.GetObject("ErrorIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:.
        /// </summary>
        internal static string ErrorPrefix {
            get {
                return ResourceManager.GetString("ErrorPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element cannot be nested within CodeElement scope..
        /// </summary>
        internal static string InvalidElementParentMessage {
            get {
                return ResourceManager.GetString("InvalidElementParentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of element must be LuaCodeFunction type..
        /// </summary>
        internal static string InvalidFunctionElementMessage {
            get {
                return ResourceManager.GetString("InvalidFunctionElementMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function cannot be nested within CodeElement scope..
        /// </summary>
        internal static string InvalidFunctionParentMessage {
            get {
                return ResourceManager.GetString("InvalidFunctionParentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function not found with name &apos;{0}&apos;..
        /// </summary>
        internal static string OldFunctionNotFoundMessage {
            get {
                return ResourceManager.GetString("OldFunctionNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refactor.
        /// </summary>
        internal static string RefactoringContextMenuName {
            get {
                return ResourceManager.GetString("RefactoringContextMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename allowed..
        /// </summary>
        internal static string RenameAllowedMessage {
            get {
                return ResourceManager.GetString("RenameAllowedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename....
        /// </summary>
        internal static string RenameCommandName {
            get {
                return ResourceManager.GetString("RenameCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflict with {0} {1} in {2}..
        /// </summary>
        internal static string RenameConflictDefinitionText {
            get {
                return ResourceManager.GetString("RenameConflictDefinitionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found conflicts.
        /// </summary>
        internal static string RenameConflictFoundCaption {
            get {
                return ResourceManager.GetString("RenameConflictFoundCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WowAddonStudio has found that the refactoring has some conflicts with the existing code.
        ///You can look through the list of conflicts and fix them by manually editing, choose &apos;Cancel&apos;..
        /// </summary>
        internal static string RenameConflictFoundMessage {
            get {
                return ResourceManager.GetString("RenameConflictFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click to navigate..
        /// </summary>
        internal static string RenameConflictsToolTipText {
            get {
                return ResourceManager.GetString("RenameConflictsToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New name of element cannot be empty!.
        /// </summary>
        internal static string RenameNewNameEmptyMessage {
            get {
                return ResourceManager.GetString("RenameNewNameEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename is not allowed for selected object..
        /// </summary>
        internal static string RenameNotAllowedMessage {
            get {
                return ResourceManager.GetString("RenameNotAllowedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming element: {0}.
        /// </summary>
        internal static string RenameStartedMessage {
            get {
                return ResourceManager.GetString("RenameStartedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RootElement for &apos;{0}&apos; cannot be found..
        /// </summary>
        internal static string RootElementCannotBeFoundMessage {
            get {
                return ResourceManager.GetString("RootElementCannotBeFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string StatusPrefix {
            get {
                return ResourceManager.GetString("StatusPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol is a reserved keyword, rename not allowed..
        /// </summary>
        internal static string SymbolReservedMessage {
            get {
                return ResourceManager.GetString("SymbolReservedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPL Outline.
        /// </summary>
        internal static string ToolWindowTitle {
            get {
                return ResourceManager.GetString("ToolWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Outliner.
        /// </summary>
        internal static string ToolWindowTitle1 {
            get {
                return ResourceManager.GetString("ToolWindowTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TreeViewIcons {
            get {
                object obj = ResourceManager.GetObject("TreeViewIcons", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string ViewMenuCommandBarName {
            get {
                return ResourceManager.GetString("ViewMenuCommandBarName", resourceCulture);
            }
        }
    }
}
